name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 99"
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/mypy-check@master
        with:
          path: fig2sketch.py
  test:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          cache: pip
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin
          pip install certifi
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          scripts/install_fig_kiwi.sh
      - name: Test
        run: |
          pytest
